import { useEffect, useState } from 'react'
import { Activity, AlertTriangle, Calendar, CheckCircle2, Search, ShieldAlert } from 'lucide-react'
import './audit-page.css'

const API = 'http://localhost:8000'
const timeLabel = value => new Date(value).toLocaleString('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })

export default function AuditPage() {
  const [logs, setLogs] = useState([])
  const [filters, setFilters] = useState({ search: '', action: '', from: '', to: '' })
  const [error, setError] = useState('')
  const load = async () => { const params = new URLSearchParams({ search: filters.search, action_type: filters.action, date_from: filters.from, date_to: filters.to }); try { const response = await fetch(`${API}/audit-logs?${params}`); if (!response.ok) throw new Error('Could not load audit logs.'); setLogs(await response.json()) } catch (loadError) { setError(loadError.message) } }
  useEffect(() => { load() }, [filters.search, filters.action, filters.from, filters.to])
  return <><div className="page-title"><div><div className="eyebrow">SECURITY / AUDIT TRAIL</div><h1>Audit logs</h1><p>Track every verification action and system event across your workspace.</p></div><div className="audit-live"><span /> Live activity</div></div>{error && <div className="audit-error"><AlertTriangle size={16} />{error}</div>}<section className="panel audit-panel"><div className="audit-toolbar"><div className="audit-search"><Search size={16} /><input placeholder="Search activity or document..." value={filters.search} onChange={event => setFilters({ ...filters, search: event.target.value })} /></div><select value={filters.action} onChange={event => setFilters({ ...filters, action: event.target.value })}><option value="">All action types</option><option>Document Uploaded</option><option>Verification Started</option><option>OCR Extraction Completed</option><option>Anomalies Detected</option><option>Verification Completed</option><option>Documents Compared</option><option>Record Deletion</option><option>Verification Failed</option></select><label className="date-filter"><Calendar size={14} /><input type="date" value={filters.from} onChange={event => setFilters({ ...filters, from: event.target.value })} /></label><span className="date-separator">to</span><label className="date-filter"><Calendar size={14} /><input type="date" value={filters.to} onChange={event => setFilters({ ...filters, to: event.target.value })} /></label></div><div className="audit-summary"><span>{logs.length} activities</span><span className="severity-key"><i className="info" />INFO <i className="warning" />WARNING <i className="critical" />CRITICAL</span></div>{logs.length ? <div className="audit-list">{logs.map(log => <div className="audit-entry" key={log.id}><div className={`audit-entry-icon ${log.severity.toLowerCase()}`}>{log.severity === 'CRITICAL' ? <ShieldAlert size={17} /> : log.severity === 'WARNING' ? <AlertTriangle size={17} /> : <Activity size={17} />}</div><div className="audit-entry-main"><div><b>{log.action}</b><span className={`severity-label ${log.severity.toLowerCase()}`}>{log.severity}</span></div><p>{log.detail}</p>{log.documentName && <small><CheckCircle2 size={12} /> {log.documentName}{log.status && ` · ${log.status}`}{log.riskLevel && ` · ${log.riskLevel} risk`}</small>}</div><time>{timeLabel(log.createdAt)}</time></div>)}</div> : <div className="audit-empty"><Activity size={24} /><b>No activity found</b><span>Try changing your filters.</span></div>}</section></>
}
