import { useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, ChevronRight, FileText, UploadCloud } from 'lucide-react'
import './compare-documents.css'

const API = 'http://localhost:8000'
const money = value => value ? `₹${Number(value).toLocaleString('en-IN')}` : 'Not detected'
const timeAgo = date => `${Math.max(1, Math.round((Date.now() - new Date(date).getTime()) / 3600000))}h ago`

export default function CompareDocuments() {
  const [documents, setDocuments] = useState([])
  const [recent, setRecent] = useState([])
  const [leftId, setLeftId] = useState('')
  const [rightId, setRightId] = useState('')
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const load = async () => { try { const [docsResponse, comparisonsResponse] = await Promise.all([fetch(`${API}/documents`), fetch(`${API}/comparisons`)]); if (!docsResponse.ok || !comparisonsResponse.ok) throw new Error('Could not load comparison data.'); const docs = await docsResponse.json(); setDocuments(docs); setRecent(await comparisonsResponse.json()); if (!leftId && docs.length > 1) { setLeftId(String(docs[0].id)); setRightId(String(docs[1].id)) } } catch (loadError) { setError(loadError.message) } }
  useEffect(() => { load() }, [])
  const upload = async (event, side) => { const file = event.target.files?.[0]; if (!file) return; const form = new FormData(); form.append('file', file); form.append('document_type', 'Invoice'); setLoading(true); setError(''); try { const response = await fetch(`${API}/upload`, { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Upload failed.'); await load(); if (side === 'left') setLeftId(String(data.id)); else setRightId(String(data.id)) } catch (uploadError) { setError(uploadError.message) } finally { setLoading(false) } }
  const compare = async () => { if (!leftId || !rightId || leftId === rightId) { setError('Select two different documents to compare.'); return } setLoading(true); setError(''); try { const response = await fetch(`${API}/comparisons`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ left_document_id: Number(leftId), right_document_id: Number(rightId) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Comparison failed.'); setResult(data); setRecent(items => [{ id: data.comparisonId, leftFileName: data.left.fileName, rightFileName: data.right.fileName, similarityScore: data.similarityScore, result: data.result, findings: data.findings, createdAt: data.createdAt }, ...items]) } catch (compareError) { setError(compareError.message) } finally { setLoading(false) } }
  return <><div className="page-title"><div><div className="eyebrow">DOCUMENT CENTER / AI COMPARISON</div><h1>Compare documents</h1><p>Compare extracted fields and OCR text across two verified documents.</p></div><button className="primary" onClick={compare} disabled={loading}><CheckCircle2 size={17} /> {loading ? 'Comparing...' : 'Run comparison'}</button></div>{error && <div className="compare-error"><AlertTriangle size={16} />{error}</div>}<div className="compare-pickers"><Picker label="Document A" value={leftId} documents={documents} onChange={setLeftId} onUpload={event => upload(event, 'left')} /><div className="compare-vs">VS</div><Picker label="Document B" value={rightId} documents={documents} onChange={setRightId} onUpload={event => upload(event, 'right')} /></div>{result && <ComparisonResult result={result} />}{!result && <RecentComparisons items={recent} />}</>
}

function Picker({ label, value, documents, onChange, onUpload }) { return <section className="panel compare-picker"><div className="picker-head"><span className="file-icon"><FileText size={18} /></span><div><small>{label.toUpperCase()}</small><b>Select a stored document</b></div></div><select value={value} onChange={event => onChange(event.target.value)}><option value="">Choose document...</option>{documents.map(document => <option value={document.id} key={document.id}>{document.fileName} · {document.documentType}</option>)}</select><label className="upload-mini"><UploadCloud size={15} /> Upload another<input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={onUpload} /></label></section> }
function ComparisonResult({ result }) { return <section className="panel compare-result"><div className="compare-result-head"><div><div className="eyebrow">COMPARISON REPORT</div><h2>{result.left.fileName} <span>vs</span> {result.right.fileName}</h2><p>{result.result} · OCR text similarity {result.ocrTextSimilarity}%</p></div><div className={`comparison-score ${result.similarityScore >= 80 ? 'good' : 'warn'}`}><strong>{result.similarityScore}%</strong><small>similarity</small></div></div><div className="compare-fields">{result.fields.map(field => <div className="compare-field" key={field.field}><div><span className={`field-dot ${field.status}`} /> <b>{field.field}</b></div><span>{field.leftValue || 'Missing'}</span><ChevronRight size={14} /><span>{field.rightValue || 'Missing'}</span><strong className={field.status}>{field.status === 'matched' ? 'MATCHED' : field.status === 'missing' ? 'MISSING' : 'MISMATCH'}</strong></div>)}</div><div className="ocr-compare"><div><h3>OCR text comparison</h3><p>Text recovered from both documents</p></div><div><pre>{result.left.extractedText || '[No text extracted]'}</pre><pre>{result.right.extractedText || '[No text extracted]'}</pre></div></div>{result.findings.length > 0 && <div className="comparison-findings"><h3>Suspicious differences</h3>{result.findings.map(finding => <p key={finding.code + finding.message}><AlertTriangle size={14} />{finding.message}</p>)}</div>}</section> }
function RecentComparisons({ items }) { return <section className="panel recent-comparisons"><div className="panel-heading"><div><h3>Recent comparisons</h3><p>Saved comparison results from your workspace</p></div></div>{items.length ? items.map(item => <div className="recent-comparison" key={item.id}><span className="file-icon"><FileText size={16} /></span><div><b>{item.leftFileName} <span>vs</span> {item.rightFileName}</b><small>{timeAgo(item.createdAt)} · {item.findings?.length || 0} findings</small></div><strong className={item.similarityScore >= 80 ? 'score-good' : 'score-mid'}>{item.similarityScore}%</strong><span className={item.result === 'MATCHED' ? 'status success' : 'status warning'}><i />{item.result}</span></div>) : <div className="empty-comparisons">No saved comparisons yet.</div>}</section> }
